### ISSUE TITLE
Mac running test.py error

### ISSUE THREAD

**Issue by cauchyyuan** [richzhang/colorization-pytorch#18]
I tried to running the test.py but got this error. Any thoughts?
```
Traceback (most recent call last):
  File "/Users/spikeyuan/PycharmProjects/pythonProject6/colorization-pytorch/test.py", line 61, in <module>
    model.test(True)  # True means that losses will be computed
  File "/Users/spikeyuan/PycharmProjects/pythonProject6/colorization-pytorch/models/base_model.py", line 56, in test
    self.forward()
  File "/Users/spikeyuan/PycharmProjects/pythonProject6/colorization-pytorch/models/pix2pix_model.py", line 123, in forward
    self.fake_B_dec_max = self.netG.module.upsample4(util.decode_max_ab(self.fake_B_class, self.opt))
  File "/opt/anaconda3/envs/pythonProject6/lib/python2.7/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'SIGGRAPHGenerator' object has no attribute 'module'
```

**Comment by Zhairest** [comment]
me too.
did you make it out in the end?
